services:
  jmcomic-web:
    image: ghcr.io/mogvl/jm-web/jm-web-frontend:latest
    container_name: jmcomic-web
    ports:
      - "5000:80"
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped

  jmcomic-server:
    image: ghcr.io/mogvl/jm-web/jm-web-server:latest
    container_name: jmcomic-server
    environment:
      - GIN_MODE=release
      - DB_PATH=/data/jmcomic.db
      - DOWNLOAD_DIR=/data/downloads
      - JM_BASE_URL=https://www.cdnhjk.net
      - TZ=Asia/Shanghai
    volumes:
      - /volume1/jm:/data/downloads
      - /volume1/docker/jm:/data
    restart: unless-stopped
